### ISSUE TITLE
Support ignoring results via inline comments?

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/zizmor#124]
`zizmor` now supports a config file that can be used to write ignore rules. However, some users also want inline ignore support, e.g.:

```yaml
permissions: write-all # zizmor: ignore[excessive-permissions]
```

See #12 for some earlier context.

**Comment by ubiratansoares** [comment]
Hey @woodruffw, I have a draft proposal [here](https://github.com/woodruffw/zizmor/compare/main...ubiratansoares:zizmor:ufs/patch-06?expand=1)

Essentially I did not use the existing `yamlpath::Document` comment extraction API since it can extract only the first comment line. Instead, I cached the entire YAML content string within the `models::Workflow` instances, finding the related starting + ending rows from the coordinates derived from `Finding::location` and checking whether we match the ignore opt-in on those particular document rows.

Asking about your thoughts before raising, because the approach is a bit dirty, but it seems to work. Maybe I'm missing some corner case from inner details from the inners of `Location` or something.

**Comment by woodruffw** [comment]
Thanks @ubiratansoares! Could you open a draft PR for it? I find things a bit easier to review in the PR view 🙂 

(The overall approach LGTM, although I have some thoughts about how we can refactor it a bit to avoid the need to plumb the workflow into the results collection phase.)

**Comment by woodruffw** [comment]
#187 adds support for `# zizmor: ignore[rule]` comments. I'll be adding some documentation for these shortly, and they'll be live in the next release.
