### ISSUE TITLE
New audit: `GITHUB_ENV`

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/zizmor#156]
`GITHUB_ENV` can be dangerous to use, particularly if it's used in `pull_request_target`, `workflow_run`, or other triggers than run in the parent repo context but can be triggered by an untrusted third party.

In particular: if the attacker can control the environment variable (or add multiple new variables), they can typically achieve code execution (via `LD_PRELOAD`, or language-specific environment variables).

This can manifest in unintuitive or unusual ways, e.g.:

```bash
echo "pr_number=$(cat NR)" >> $GITHUB_ENV
```

if `NR` contains multiple lines, each gets added to the environment.

Or even:

```
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          message=$(echo "$TITLE" | grep -oP '[{\[][^}\]]+[}\]]' | sed 's/{\|}\|\[\|\]//g')
          echo "message=$message" >> $GITHUB_ENV
```

...since `grep -P` will cause each match to receive a new line, meaning that `TITLE='[benign][LD_PRELOAD=...]'` will inject the latter as an environment variable as well.

One wrinkle with flagging these is noisiness: `GITHUB_ENV` use in the context of `pull_request` and other "safe" triggers can result in code injection, but the attacker has no secret or otherwise privileged access to the workflow. As such, a new audit here should only flag on triggers that could allow external, privileged, code execution.

h/t @Ninja3047

Refs:

* https://x.com/GHSecurityLab/status/1856787029851320367
* https://www.synacktiv.com/en/publications/github-actions-exploitation-repo-jacking-and-environment-manipulation

**Comment by polarathene** [comment]
## Basic `LD_PRELOAD` example

I know your 2nd URL ref points to [another site with an example program](https://0xn3va.gitbook.io/cheat-sheets/web-application/command-injection#ld_preload), but when I was made aware of such a vulnerability I would have appreciated a simple to grok example program, especially one not buried in all the other information on the topic 😅 

---

Sharing here if it helps anyone else, as when this was new to me at the time I had encountered a few hiccups along the way. I went with Rust due to familiarity and how simple / focused it is to grok.

<details>
<summary>LD_PRELOAD exploit example (Rust)</summary>

Basic program with Rust to demonstrate `LD_PRELOAD` exploit. Create these two files with Rust installed to build it.

**`Cargo.toml`:**

```toml
[package]
name = "example"
version = "0.1.0"
edition = "2021"

# Required for the extern C `init_log()` function to link dynamically:
[lib]
name = "example"
crate-type = ["cdylib"]
```

**`src/lib.rs`:**

```rust
// NOTE: The function name is your choice, it must be referenced in `RUSTFLAGS` as the value after `-Wl,-init,`
#[no_mangle]
pub extern "C" fn init_log() {
    println!("This will output to stdout before the program starts");
}
```

```console
# Build `libexample.so`:
$ RUSTFLAGS='-C link-arg=-Wl,-init,init_log' cargo build

# Verify `LD_PRELOAD` hook is working:
$ LD_PRELOAD=target/debug/libexample.so /usr/bin/echo test
This will output to stdout before the program starts
test

# NOTE: As `echo` is a shell built-in the dynamic linker would not be called,
# Only when running an actual dynamically linked executable like `/user/bin/echo` like above works.
$ LD_PRELOAD=target/debug/libexample.so echo test
test
```

A real-world attack would be free to execute any code within the compromised trusted workflow.

</details>

---

## Mitigation Advice?

A common use-case this will be seen in workflows AFAIK is for actions with PRs where some later functionality does need access to secrets, but the PR is from a fork which loses the `pull_requests` event context in `workflow_run` or similar trusted contexts that adopted the ENV approach.

While awareness of the vulnerability is quite helpful, I often don't see much advice on how maintainers should resolve it properly. Can they safely use the `GITHUB_ENV` technique by filtering the untrusted input downloaded via artifact? Or can the attacker manipulate the input that it'll not be filtered properly?

That was a concern I had, where I wasn't particularly confident unless you can more strictly validate the expected value for a key (_eg: only digits for PR number, or hexadecimal for a commit SHA_). There's a variety of approaches that users discuss in communities when they tackle this issue, some lack the needed context for PRs from forks, risk failure due to rate limits, or require extra care due to security risks (_this ENV artifact approach, or `pull_request_target` running untrusted code_).

I assume the closest to mitigation advice in `zizmor` is the audit rules page with "Other Resources" links? Seems related to: https://github.com/woodruffw/zizmor/issues/125

---

In my case, the affected workflow was a standard documentation preview for PRs with an action that comments on the PR with a link to the preview.

I've [chosen to go with `pull_request_target` as the workflow trigger](https://github.com/docker-mailserver/docker-mailserver/pull/4264) that calls two `workflow_call` workflows:
- The first job intended to mimic `pull_request` by cloning the PR branch and building the contribution (_while preventing access to `secrets` and only permitting `content: read` for the git checkout_).
- An artifact upload is still used to transfer that build between jobs into the secure/trusted workflow with access to secrets, but `GITHUB_ENV` is avoided as `pull_request_target` now passes context to each job via `workflow_call` inputs (these workflows by default do not inherit `secrets`, but they do inherit `permissions` IIRC and cannot add new permissions from the calling workflow, only reduce them.

**Comment by woodruffw** [comment]
> While awareness of the vulnerability is quite helpful, I often don't see much advice on how maintainers should resolve it properly. Can they safely use the `GITHUB_ENV` technique by filtering the untrusted input downloaded via artifact? Or can the attacker manipulate the input that it'll not be filtered properly?

This is definitely tough to mitigate properly. I'd say the baseline advice is that "dangerous" triggers (like `pull_request_target`) shouldn't use `GITHUB_ENV` at all, if they can avoid it. If they're using it to pass state around, using `GITHUB_OUTPUT` is much safer.

If `GITHUB_ENV` can't be avoided for whatever reason, the safest thing to do is:

1. Ensure that the workflow can't set the environment variable's name, and can't control the variable's value excessively if the variable is a sensitive one
2. Ensure that the environment variable name chosen is unique and unlikely to have side effects
3. Ensure that the workflow can't set multiple *new* environment variables, e.g. via `echo "pr_number=$(cat NR)" >> $GITHUB_ENV` or the `grep -P` loophole mentioned above

> I assume the closest to mitigation advice in `zizmor` is the audit rules page with "Other Resources" links? Seems related to: #125

Yep, for now that's the best place! I'd greatly appreciate help improving those docs, including adding examples of vulnerable workflows and their mitigations.

**Comment by polarathene** [comment]
> This is definitely tough to mitigate properly.

I've added a new reference link to the top of my previous comment. It's an official GitHub Security Lab (GHSL) advisory with reference to the original vulnerability report at the project, similar to the one I received.

Their mitigation only [required the PR number to be validated](https://github.com/litestar-org/litestar/commit/84d351e96aaa2a1338006d6e7221eded161f517b), which might be suitable for most.

> I'd say the baseline advice is that "dangerous" triggers (like `pull_request_target`) shouldn't use `GITHUB_ENV` at all, if they can avoid it. If they're using it to pass state around, using `GITHUB_OUTPUT` is much safer.

I had a two-step workflow run with `pull_request` => `workflow_run` triggers like the referenced advisory was doing. The metadata available within `pull_request` is uploaded as an artifact and downloaded at the 2nd workflow triggered to load for input into an action.

I agree that outputs should work just as fine, considering they're configured in the same format. ENV is likely used as it's a more familiar choice and you'll see it suggested as a solution around the web.

Github would advise on their security blogs for a script to use the ENV as a variable however, rather than via the context `${{ ... }}` syntax when it's within the value of a script as the latter is less secure (_regardless of env vs output context_).

---

> Ensure that the workflow can't set the environment variable's name, and can't control the variable's value excessively if the variable is a sensitive one

I think the problem is more to do with blindly appending to `GITHUB_ENV` when the source content can be manipulated by the PR author.

When this was reported to me I was not aware that third-party contributors could modify `pull_request` workflows to run whatever they want, which AFAIK will run without approval if the contributor has previously had a PR merged (_such as simple typo fix_). That made me reluctant to keep the `pull_request` trigger for this purpose, even though `pull_request_target` has it's own risks involved.

Validating the input [like `litestar` did to mitigate](https://github.com/litestar-org/litestar/commit/84d351e96aaa2a1338006d6e7221eded161f517b) seems to be the most appropriate way if keeping the `GITHUB_ENV` usage. They were already storing only the value itself for a single variable in a file, where the value was not ambiguous in content, so ensuring it was a number was was valid. Once that value is safe, they append to `GITHUB_ENV` with the expected variable name, avoiding any untrusted input slipping through (_technically the PR author could still manipulate the PR number to be a different one_).

---

> I'd greatly appreciate help improving those docs, including adding examples of vulnerable workflows and their mitigations.

I'm not sure how appropriate it is to use the `litestar` reference as an example, but I know that there's a fair amount of workflows with roughly the same approach / requirement out there.

A basic search reveals about 800+ workflows, but that's without double-checking if they're populating the `.env` from untrusted workflows like `pull_request` or other dynamic sources.

**Comment by woodruffw** [comment]
> When this was reported to me I was not aware that third-party contributors could modify `pull_request` workflows to run whatever they want, which AFAIK will run without approval if the contributor has previously had a PR merged (_such as simple typo fix_).

They can, but it's worth noting that `pull_request` workflows aren't as dangerous: a `pull_request` triggered from a fork runs in that fork's context, meaning that the attacker can't use `pull_request` to access the `secrets.*` context or anything else sensitive on the upstream repo. They can still run arbitrary code, but that code has no effect on the upstream repo.

In addition, you can disable the "safe after first time" default under `Settings -> Actions`:

![](https://thing-in-itself.net/u/8it98r9PnLQ.png)

**Comment by polarathene** [comment]
> They can still run arbitrary code, but that code has no effect on the upstream repo.

Yes, but that's the issue when the common problem with `$GITHUB_ENV` is due to `pull_request` event being used as the initial workflow trigger, and then storing metadata into a file to carry over context into a trusted workflow with access to secrets to perform some additional functionality.

If the functionality could be done solely in `pull_request` alone, that'd be fine. Getting access to that `pull_request` context in a subsequent workflow that requires the additional context has been a known problem for years, it'd be ideal if we had more official guidance / patterns on such.

For reference: The `pull_request` => `workflow_run` approach was covered at the [GHSL blog (Aug 2021)](https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/), passing the PR number via file.

At least with `zizmor` this concern will be caught more easily 😎 

---

> In addition, you can disable the "safe after first time" default under `Settings -> Actions`:

I was not aware of that (_or when it was added_), good to know thanks :)

**Comment by polarathene** [comment]
**FWIW:** I've completed my investigation into mitigation for the common workflow scenario with `pull_request` + `workflow_run` (_as a 2nd stage triggered by the `pull_request` workflow, get the PR number to do something like post a comment on the PR_).

---

I've [documented three different approaches](https://github.com/docker-mailserver/docker-mailserver/pull/4267#issuecomment-2484565209) (_and [this summary](https://github.com/orgs/community/discussions/25220#discussioncomment-11316244)_) revised from what I found shared by the community, with full examples and insights should it help anyone.

These have also been reviewed by GHSL:
- With insights shared of additional dangers from using `pull_request_target` (_cache poisoning at the branch boundary + memory dump access of secrets_)
- While the endorsed solution is to use `gh pr view`, otherwise fallback to passing values through artifacts to validate and append to `$GITHUB_OUTPUT` / `$GITHUB_ENV`.

**Comment by ubiratansoares** [comment]
@woodruffw I can take this one. I give it a try [here](https://github.com/woodruffw/zizmor/pull/192), hope it is in the right direction!

**Comment by woodruffw** [comment]
Done with #192.
