### ISSUE TITLE
Feature: Release pre-built binaries

### ISSUE THREAD

**Issue by nikolay** [woodruffw/zizmor#210]
### Pre-submission checks

- [X] I am **not** reporting a bug (crash, false positive/negative, etc). These must be filed via the bug report template.
- [X] I have looked through the open issues for a duplicate request.

### What's the problem this feature will solve?

Needing the entire Rust toolchain.

### Describe the solution you'd like

Like many other Rust projects, this one should also release binaries for Linux, macOS, and Windows on different architectures.

**Comment by woodruffw** [comment]
Thanks @nikolay!

See https://github.com/woodruffw/zizmor/discussions/169 for some related discussion -- the current releases don't contain binaries because I want downstream packaging ecosystems to package this directly (IME, upstream-controlled packaging results in a second-class user experience).

In the meantime, for macOS you *can* do `brew install zizmor` and get a binary without needing a Rust toolchain. But the same for Linux and Windows is not something I'm planning in the short term, since both are nontrivial and I'd like to see some rolling upstreams pick it up first.

**Comment by woodruffw** [comment]
Closing in favor of continuing discussion in #169.
