### ISSUE TITLE
Do not change the output format when stdout is a pipe

### ISSUE THREAD

**Issue by asmeurer** [woodruffw/zizmor#76]
I tried piping the output of zizmor to `pbcopy` to copy into an issue, but the resulting output was changed from the human readable output to JSON. I also often pipe command output into `less`.

The format of the output should be controlled by a command line flag, not by the type of the stdout file.

**Comment by miketheman** [comment]
@asmeurer Did you try `--format=plain`?

See https://github.com/woodruffw/zizmor#output-formats as well

**Comment by woodruffw** [comment]
Thanks for the report @asmeurer! Yeah, per what @miketheman said this is intentional behavior: the "default" output format depends on the capabilities detected by `zizmor`: if `stdout` is a terminal then it uses the "diagnostic" format, and if it's not then it uses the JSON format. To always emit a specific format you should use the `--format=...` option, or explicitly set something like `TERM=dumb`.

I'm open to changing the default here to always be `plain`, though as part of that I'd like to understand whether this is causing issues for people outside of filing issues. If it's only causing issues in that case, then IMO the right thing to do for now is for me to document this behavior better 🙂

**Comment by asmeurer** [comment]
Well like I said, I often like to pipe long command output through `less`. I find it pretty surprising for a pipe completely change the output of a command (stripping ANSI color sequences notwithstanding). I can't really think of any other command that does this.

**Comment by woodruffw** [comment]
> Well like I said, I often like to pipe long command output through `less`. I find it pretty surprising for a pipe completely change the output of a command (stripping ANSI color sequences notwithstanding).

That's a good point, thanks. I hadn't considered that this would snare the `less` case -- I would also find it unintuitive if adding a pipeline member like that completely changed the output format.

Given that, I'm hereby declaring that I was wrong and that this should be changed :slightly_smiling_face:. Would you be interested in sending a patch @asmeurer? Otherwise I'll likely get to this in the next day or so.
