### ISSUE TITLE
Return different codes based on findings

### ISSUE THREAD

**Issue by daviddavis** [woodruffw/zizmor#86]
We'd like to use zizmor to gate PRs and prevent GHA code from being merged if it has serious security bugs. Currently, I am outputting the json and then using jq to parse the output and then checking the result in bash. 

What would be more ideal is to use zizmor's return code (`$?`). I think most other linters, scanners, etc return non-zero codes based on results. I might suggest returning 0 for any low/medium priority findings and 1 for high. And then maybe in pedantic mode, returning 1 for any findings.

Great tool by the way. We have been looking for something like this for a while and I'm trying to learn rust so I can contribute.

**Comment by woodruffw** [comment]
Thanks for the issue @daviddavis, and for the kind words! 

I agree, this would be a great feature to add -- I'd be happy to have it return with the following codes:

1. `0`: no warnings/errors at all;
2. `11`: all warnings are "low" or below;
3. `12`: all warnings are "medium" or below;
4. `13`: there's at least one "high"

(The reason they start at `11` is because I don't want to shadow any existing - incidental - low error code behavior: I think currently we exit with `1` on any internal tool failures.)

If you'd be interested in sending a PR for this, I'd be happy to review it! Otherwise, I can tackle this myself in the next day or so.

**Comment by woodruffw** [comment]
(Also thinking out loud: I'm not 100% sure if exit codes should be used with `--format=sarif` -- some tools might treat an exit code in that case as an error within the tool itself. But we can start out by making exit codes universal and seeing what happens 🙂)

**Comment by woodruffw** [comment]
Doing this in #133 -- see the docs once merged for the final exit code choices :slightly_smiling_face:

**Comment by gsong** [comment]
@woodruffw Thank you for the wonderful work and your receptivity to feature requests. This will be helpful during CI for sure!

**Comment by woodruffw** [comment]
Thanks @gsong, glad to hear it's helpful!

FWIW, I noticed you're building some actions here: <https://github.com/gsong/gha-zizmor-actions>. That's awesome, but can I ask you to not refer to them as official (at least, until/if they get upstreamed)? The README says that, and I think that might cause some confusion for folks trying to figure out what is or isn't an upstream project. 

(I assume that was generated from a template or LLM or similar, since it also mentions a `zizmor` version that doesn't exist yet 🙂)

**Comment by gsong** [comment]
@woodruffw You caught me. Yes, I used LLM to generate the README and didn't read it too carefully. Will edit this week.

**Comment by gsong** [comment]
@woodruffw Fixed. Open to suggestions on how to improve the actions.
